<?php

// This file is extracted and generated by the PHP-SFW composer installer.
// This is the root entry point of the website.
// You can customize it for example to add queries namespaces or add routes.
// More information at : https://github.com/mindstorm38/php-sfw

require __DIR__ . '%{REL_PATH_TO_AUTOLOADER}%/vendor/autoload.php';

use SFW\Core;

Core::start_application( "%{APP_NAME}%", __DIR__ );
Core::try_route_requested_path();

?>
